### ISSUE TITLE
E2EE tutorial and guides

### ISSUE THREAD

**Issue by MichalNemec** [famedly/matrix-dart-sdk#1582] opened 2023-10-15 02:53 UTC
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions

### Describe your problem

I spent a lot of time trying to find how to do E2EE properly, without luck. When i found some information, it was for js or python, which is different than in dart. Ive managed to have encryption correctly for private chat, but im having trouble when user logs out and logs back in. i get for every message 'Could not decrypt message: No permission'.

my init is like this:
```
init() async {
    client = Client(
      'client_name',
      databaseBuilder: (_) async {
        //final dir = await getApplicationSupportDirectory();
        final dir = await getApplicationDocumentsDirectory();
        final db = HiveCollectionsDatabase('collection', '${dir.path}/');
        await db.open();
        return db;
      },
    );
    await client.init();
  }
connect() async {
    if (client.isLogged()) {
      return;
    }
    client.checkHomeserver(Endpoints.matrixUrl);
    const storage = FlutterSecureStorage();
    final deviceId = await storage.read(key: StoreKey.deviceId.value);
    try {
      final response = await client.login(
        LoginType.mLoginJwtToken,
        identifier: AuthenticationUserIdentifier(user: AuthData().getUserId()!),
        token: AuthData().accessToken!,
        deviceId: deviceId,
        refreshToken: true,
      );
      await storage.delete(key: StoreKey.deviceId.value);
      await storage.write(key: StoreKey.deviceId.value, value: response.deviceId);
    } catch (e) {
      Console.out().e(e);
    }
  }
```
i can see in database / hive files that i am storing keys. 

The trouble is when i have only one client (this one im building) and when i log out and then log back in, then i cant see rooms, upon reload of client i see rooms and every message has that could not decrypt message.

I could not find anywhere:
- should i call encryption somewhere?
- should i call bootstrap?
- should i manage or do something with keys?
- how to decrypt message?

Im purposefully not doing verification or passcode or matching with the user (comparing emojis, or whatever) and dont want to.

Based on example it just shows simple implementation, which upon logging out and back in breaks things.

### Describe your ideal solution

Make a guide for encryption for dart so that its clear to understand and develop. Scouting code and trying to figure it out is not a good way especially when half of the functions is not commented.

### Version

0.22.4

### Security requirements

Make E2EE functioning correctly.

**Comment by MichalNemec** [comment] 2023-10-16 01:02
after long session of debugging, JWT token implementation is bad in matrix packages. When i use password then encryption bootstrap works.

**Comment by krille-chan** [comment] 2023-11-07 14:49
Hey thanks for your interest, but currently we do not have the capacity to give technical support. However a more detailed handbook which covers this topic is on our roadmap but might need much more time before we can start with it.
Closing as this is not a bug

**Closed by krille-chan** 2023-11-07 14:49 UTC
Labels: improvement
