### ISSUE TITLE
Errors when logging in matrix

### ISSUE THREAD

**Issue by abigotado** [famedly/matrix-dart-sdk#1693] opened 2024-01-22 22:54 UTC
### Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions.
- [ ] I already asked for help in the chat

### In which Project did the bug appear?

Other

### If you selected \"Other\" as Project, please enter in which project the bug occurred.

matrix_dart_sdk

### On which platform did the bug appear?

Android, iOS, Chrome

### SDK Version

latest

### Describe the problem caused by this bug

I have an app with matrix chat for web and mobile. Every time the app restarts or user logs in his account (app account, not matrix), the method to log in matrix is being called. If the user has already been logged in, the errors occur:

```
flutter: [Matrix] \^[[32mInitialize client SquadderChat<…>
flutter: [Matrix] \^[[34mOpen Hive...<…>
[ ERROR ]  AuthRepository logInMatrix 
[ ERROR ] ClientInitPreconditionError (Client Init Precondition Error: [init()] has been called multiple times!)
[ ERROR ] #0      Client.init (package:matrix/src/client.dart:1474:7)
                         #1      Client.login (package:matrix/src/client.dart:545:11)
                         <asynchronous suspension>
                         #2      AuthRepository.logInMatrix (package:squadder/features/authorization/data/auth_repository.dart:69:9)
                         <asynchronous suspension>
                         #3      AuthCubit._logInMatrix (package:squadder/features/authorization/presentation/blocs/auth_bloc.dart:144:5)
                         <asynchronous suspension>
flutter: [Matrix] \^[[34mHive is ready<…>
flutter: [Matrix] \^[[34mBenchmark: Build database -> 207 ms<…>
flutter: [Matrix] \^[[34mBenchmark: Get Client from store -> 3 ms<…>
flutter: [Matrix] \^[[34mBenchmark: Get all account data from store -> 11 ms<…>
flutter: [Matrix] \^[[34mBenchmark: Get room list from store -> 220 ms<…>
flutter: [Matrix] \^[[34mBenchmark: Get all user device keys from store -> 270 ms<…>
flutter: [Matrix] \^[[32mSuccessfully connected as abigotado with https://matrix.dev.squadder.team<…>
flutter: [Matrix] \^[[32mInitialize client SquadderChat<…>
[ ERROR ]  AuthRepository logInMatrix 
[ ERROR ] ClientInitPreconditionError (Client Init Precondition Error: User is already logged in! Call [logout()] first!)
[ ERROR ] #0      Client.init (package:matrix/src/client.dart:1485:9)
                         #1      Client.login (package:matrix/src/client.dart:545:11)
                         <asynchronous suspension>
                         #2      AuthRepository.logInMatrix (package:squadder/features/authorization/data/auth_repository.dart:69:9)
                         <asynchronous suspension>
                         #3      AuthCubit._logInMatrix (package:squadder/features/authorization/presentation/blocs/auth_bloc.dart:144:5)
                         <asynchronous suspension>
                         #4      new AuthCubit.<anonymous closure> (package:squadder/features/authorization/presentation/blocs/auth_bloc.dart:23:11)
                         <asynchronous suspension>
flutter: [Matrix] \^[[32mInitialize client SquadderChat<…>
[ ERROR ]  AuthRepository logInMatrix 
[ ERROR ] ClientInitPreconditionError (Client Init Precondition Error: User is already logged in! Call [logout()] first!)
[ ERROR ] #0      Client.init (package:matrix/src/client.dart:1485:9)
                         #1      Client.login (package:matrix/src/client.dart:545:11)
                         <asynchronous suspension>
                         #2      AuthRepository.logInMatrix (package:squadder/features/authorization/data/auth_repository.dart:69:9)
                         <asynchronous suspension>
                         #3      AuthCubit._logInMatrix (package:squadder/features/authorization/presentation/blocs/auth_bloc.dart:144:5)
                         <asynchronous suspension>
                         #4      new AuthCubit.<anonymous closure> (package:squadder/features/authorization/presentation/blocs/auth_bloc.dart:23:11)
                         <asynchronous suspension>
flutter: [Matrix] \^[[34mBenchmark: Process sync -> 24 ms (2 items, 12.0 ms/item)<…>
```

As we can see, client tries to log in three times. Getting `ClientInitPreconditionError (Client Init Precondition Error: [init()] has been called multiple times!)` the first time and then `ClientInitPreconditionError (Client Init Precondition Error: User is already logged in! Call [logout()] first!)`. But I am checking `client.isLogged()` before calling `client.login()` and it returns `false` every time, I have no idea why.

Moreover the error `ClientInitPreconditionError (Client Init Precondition Error: [init()] has been called multiple times!)` is occurring even if the user is logging in for the first time (`client.logout()` then `client.login()`).

Here is my client module (registered with `injectable`):
```dart
@module
abstract class ApiModule {
  /// Matrix client.
  @preResolve
  Future<Client> createMatrixClient() async {
    final Client client = Client(
      'SquadderChat',
      // ignore: prefer_final_parameters
      databaseBuilder: kIsWeb
          ? (final Client client) async {
              final MatrixSdkDatabase database =
                  MatrixSdkDatabase(client.clientName);
              await database.open();
              return database;
            }
          : FlutterHiveCollectionsDatabase.databaseBuilder,
      logLevel: kDebugMode ? Level.verbose : Level.error,
      nativeImplementations: kIsWeb
          ? NativeImplementationsWebWorker(Uri.parse('/'))
          : NativeImplementationsIsolate(compute),
    );
    client.homeserver = Endpoints.matrixUri;

    return client;
  }
}
```

Here is AuthRepository with login/logout:

```dart
class AuthRepository {
  /// Constructor.
  AuthRepository({
    final AuthService? service,
    final EncryptedStorage? encryptedStorage,
    final Client? matrix,
  })  : _service = service ?? GetIt.I.get<AuthService>(),
        _encryptedStorage = encryptedStorage ?? GetIt.I.get<EncryptedStorage>(),
        matrix = matrix ?? GetIt.I.get<Client>();

  final AuthService _service;
  final EncryptedStorage _encryptedStorage;
  final Client matrix;

  /// User.
  UserModel? get user => _encryptedStorage.user;

  Future<void> logInMatrix() async {
    if (!matrix.isLogged() &&
        user?.profiles?.firstOrNull?.matrixUser?.login != null) {
      try {
        await matrix.login(
          LoginType.mLoginPassword,
          identifier: AuthenticationUserIdentifier(
            user: user!.profiles!.first.matrixUser!.login,
          ),
          password: user!.profiles!.first.matrixUser!.password,
        );

        matrix.rooms.map((final Room e) async {
          if (e.membership == Membership.invite) {
            await matrix.joinRoom(e.id);
          }
        }).toList();
      } catch (e, s) {
        AppLogger.log('${toString()} logInMatrix', exception: e, stackTrace: s);
      }
    }
  }

  Future<void> logOutMatrix() async {
    await matrix.logoutAll();
  }
}
```

**Comment by krille-chan** [comment] 2024-01-23 07:58
You should first init the matrix client with the database like this:

```dart
  Future<void> logInMatrix() async {
    await matrix.init();
    if (!matrix.isLogged() &&
        user?.profiles?.firstOrNull?.matrixUser?.login != null) {
      try {
        await matrix.login(
        // ...
```

This will restore the previous session. So I assume this is not a bug but a documentation problem in the sdk. I'm going to rewrite the documentation anyway so I'll close this

**Closed by krille-chan** 2024-01-23 07:58 UTC
Labels: bug
